<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(App\Models\User::class, 10)->create();
        DB::table('users')->insert(array(
             array('first_name'=>'Vincent',
                    'last_name'=>'Vega',
                    'company_name'=>'',
                    'address'=>'13763 Hawthorne Boulevard',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78251,
                    'email'=>'v_vega@gmail.com',
                    'employer'=>0,
                    'content'=>"I'm a full stack LAMP+JS web application developer working in San Antonio. I'm passionate about building applications people use.In addition to web application development, my background is in IT administration. I also have experience building business applications with Microsoft Dynamics CRM, Microsoft SharePoint, Wordpress, and Safe Software's Feature Manipulation Engine FME (for data transformation and manipulation).",
                    'linkedin_id'=>'https://www.linkedin.com/in/vince-vega-66882251',
                    'github'=>'https://gist.github.com/wrobstory/5609803',
                    'website'=>'http://www.rollingstone.com/movies/news/pulp-fiction-a-to-z-20140521',
                    'image'=>'http://mhalabs.org/wp-content/uploads/upme/1451456913_brodie.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Brandon',
                    'last_name'=>'Marshall',
                    'company_name'=>'',
                    'address'=>'4642 La Marquesa',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78247,
                    'email'=>'b_marshall@gmail.com',
                    'employer'=>0,
                    'content'=>"Seeking jobs that help me to improve my programming skills, accomplish my professional goals, extend and apply my knowledge as a systems engineer and ongoing development field to learn new technologies.",
                    'linkedin_id'=>'https://www.linkedin.com/in/fernando-mendoza-rodriguez-a7369123',
                    'github'=>'https://gist.github.com/wrobstory/5609803',
                    'website'=>'www.brandon_marshall.com',
                    'image'=>'https://upop.mit.edu/sites/default/files/DASO%20Frederick%20LinkedIn%20Profile%20Photo.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Alexander',
                    'last_name'=>'Prescott',
                    'company_name'=>'',
                    'address'=>'5919 Huebner Rd',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78216,
                    'email'=>'zander_P@gmail.com',
                    'employer'=>0,
                    'content'=>"I am a full stack web developer.  I completed the Codeup 12-week bootcamp for the LAMP+J stack in April 2014.  I am able to look at what is need of the program and see a clear way to write code to make those functions happen.  I focus on making sure the end product is easy to use and functions without problem.  I am detail oriented and want it all to work together well.
                        Once I finish the Codeup Bootcamp I would like to get a job where I can use my skills while at the same time continue learning new technologies.",
                    'linkedin_id'=>'https://www.linkedin.com/in/cameronholland90',
                    'github'=>'https://gist.github.com/wrobstory/5609803',
                    'website'=>'www.who_is_zander.com',
                    'image'=>'http://www.american.edu/uploads/profiles/large/chris_palmer_profile_11.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Stacen',
                    'last_name'=>'Velven',
                    'company_name'=>'',
                    'address'=>'2318 Capstone Hill',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78276,
                    'email'=>'velvety18@gmail.com',
                    'employer'=>0,
                    'content'=>"I am eager to learn new technologies and their practical applications. 
                                I have over 10 years of professional experience in the nonprofit and government sectors. I am good at identifying success factors in support of specific goals and implementing appropriate solutions.
                                My natural affinity for technology allows me to leverage technologies to implement more robust creative solutions to professional problems.",
                    'linkedin_id'=>'https://www.linkedin.com/in/bennycardenas1',
                    'github'=>'https://gist.github.com/wrobstory/5609803',
                    'website'=>'www.st_velven.com',
                    'image'=>'http://matchpredictions.in/wp-content/uploads/2015/09/MS-Dhoni-Cricinfo-Yahoo-Profile-Stats-Highlights.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Brice',
                    'last_name'=>'Wilkinson',
                    'company_name'=>'',
                    'address'=>'3236 Braesview Ln',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78253,
                    'email'=>'b_dub@gmail.com',
                    'employer'=>0,
                    'content'=>"My focus is on learning and mastering JavaScript functional programming design patterns, React, jQuery, OOP, PHP, MySQL, Laravel, Node, Python, HTML5, and CSS3. All time favorite apps: Evernote, Spotify, Twitter, Trello and Slack. In love with computers since programming my first game in BASIC on an Apple IIE in 1995. I have carried this excitement, fascination and wonder with me as I watch computer science and the internet grow. As a musician, artist and all around geek, it has been my dream to apply these passions and skills in the workplace. This special cocktail of obsessions gives me a unique view of the web and has challenged me to apply myself as a web developer. Currently, I am a Student Fellow at Codeup San Antonio where I am honing my skills and spending my spare time learning new web technologies.",
                    'linkedin_id'=>'https://www.linkedin.com/in/will78006',
                    'github'=>'https://gist.github.com/wrobstory/5609803',
                    'website'=>'www.wilkinson.com',
                    'image'=>'https://lh4.googleusercontent.com/-fHlz7kScna4/AAAAAAAAAAI/AAAAAAABS38/m2l9kOds1mE/photo.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Judy',
             		'last_name'=>'Lenard',
             		'company_name'=>'Cambridge Auto',
             		'address'=>'9823 Fredericksburg Rd',
             		'city'=>'San Antonio',
             		'state'=>'TX',
             		'zip_code'=>78240,
             		'email'=>'judy@gmail.com',
             		'employer'=>1,
             		'content'=>"Cambridge Auto Center in San Antonio provides the auto repair service experiences your vehicle can’t afford to miss. We build our quality auto services on lasting relationships. You depend on your car, your car depends on us, and we depend on you! Our team of superior technicians wants your trust! If you can trust our expertise, then you’ll enjoy effective auto services and enhanced driving experiences. We’re using the industry’s most advanced tools and equipment to make sure your vehicle is always under the best care. With six ASE Master Techs on staff, there’s nothing we haven’t seen, serviced, or repaired. We have over 150 years of combined auto service experience between us. Our large facility of 23 service bays is the place where all automotive problems get solved. We know that auto maintenance and repair service does not have to be stressful. It’s our job to make sure you understand that we make auto service a pleasant experience.",
					'linkedin_id'=>'',
             		'github'=>'',
             		'website'=>'www.cambridgeauto.com',
             		'image'=>'http://www.cambridgeauto.com/wp-content/uploads/logo.png',
             		'password'=>bcrypt('password')),
             array('first_name'=>'Jason',
                    'last_name'=>'Straughan',
                    'company_name'=>'Grok Interactive',
                    'address'=>'600 Navarro St #350',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78205,
                    'email'=>'jason@gmail.com',
                    'employer'=>1,
                    'content'=>"We believe that happy developers equal happy clients, and we make it a point to cultivate a team with exceptional chemistry that enjoys doing great work. Let's work together!",
                    'linkedin_id'=>'',
                    'github'=>'',
                    'website'=>'http://www.concoursautosalon.com/',
                    'image'=>'http://www.xconomy.com/wordpress/wp-content/images/2016/03/Grok-Interactive.jpg',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Jennifer',
                    'last_name'=>'Remlinger',
                    'company_name'=>'Two Guys Moving',
                    'address'=>'301 De Zavala Suite 375',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78290,
                    'email'=>'jennifer@gmail.com',
                    'employer'=>1,
                    'content'=>"Two Guys Moving of San Antonio is a family and veteran owned and locally operated company that has been serving Texas for more than 10 years. Our team has the skill and expertise to successfully move you into your new home, apartment, office building or storage unit.The company was in business for more than 10 years before Owners Paul and Jennifer took over and began expanding upon the San Antonio-based business. Paul has a degree in mechanical engineering and has 20 years experience estimating and running construction projects. Jennifer received her BS degree from Texas State in elementary education and masters from UTSA in educational leadership. She taught 4th and 5th grade for 22 years before deciding to retire and take over Two Guys Moving. Jennifer runs the day to day operations, including scheduling moves and crews for each day and the accounting, and Paul works full time in construction but helps with insurance, vehicle maintenance, licensing and bookkeeping.",
                    'linkedin_id'=>'',
                    'github'=>'',
                    'website'=>'http://twoguysmovingu.com',
                    'image'=>'http://twoguysmovingu.com/wp-content/uploads/2013/10/two-guys-moving-logo-retina1.png',
                    'password'=>bcrypt('password')),
             array('first_name'=>'Sarah',
                    'last_name'=>'Nordman',
                    'company_name'=>'El Jalisco Taqueria',
                    'address'=>'4583 Nacogdoches',
                    'city'=>'San Antonio',
                    'state'=>'TX',
                    'zip_code'=>78215,
                    'email'=>'sarah_n@gmail.com',
                    'employer'=>1,
                    'content'=>"El Jalisco is a family-owned mexican restaurant that has been operating in San Antonio for 3 years. Our family is looking for a web designer that can help us rebrand and expand our demographic.",
                    'linkedin_id'=>'',
                    'github'=>'',
                    'website'=>'http://www.jalisco_sa.com',
                    'image'=>'http://lh4.ggpht.com/Fal0j1YWtcvfkCuDK3Rfs9ikFZ6jAb6loOhFJLY7cQlx1UENaDocec3YAsImLIKWjKI=w300',
                    'password'=>bcrypt('password')),

          ));
    }
}

